name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  build-and-test:
    name: CI
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
      
    - name: Install dependencies
      run: npm i

    - name: Clearing previous builds
      run: npm run clean
      
    - name: Run Linter
      run: npm run lint
      continue-on-error: true

    - name: Type Check
      run: npm run typecheck

    - name: Build
      run: npm run build

    - name: Run Tests
      run: npm test
